# Generated by Django 4.2.3 on 2023-10-14 05:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workschedule", "0008_calendarpersonalinfo_delete_calendardate"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CalendarPersonalinfo",
            new_name="surveyCalendar",
        ),
    ]
